contentColumnType: integer(10)
fieldGroup: 1bddc6ff-b8f1-4708-af28-108cd6e92099 # Works
handle: actsCount
instructions: ''
name: 'Nombre dâ€™actes / de parties'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '1'
  prefix: ''
  previewCurrency: ''
  previewFormat: none
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
