contentColumnType: string
fieldGroup: b3d3b5fa-565c-459c-b370-cc1dceca0750 # Persons
handle: pseudonyms
instructions: ''
name: Pseudonyme
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'SÃ©lectionner un ou plusieurs pseudonyme(s)'
  showSiteMenu: true
  source: null
  sources:
    - 'section:63ea829e-b0e4-4021-8ab5-1b0f095d3daf' # Personnes
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
