enableVersioning: true
handle: animationTechniques
name: 'Techniques dâ€™animation'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Page FR'
      -
        - urlFormat
        - '{alias(''@livePreviewUrl'')}/techniques-d-animation/{sourceId}/{slug}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - 'Page EN'
      -
        - urlFormat
        - '{alias(''@livePreviewUrl'')}/en/techniques-d-animation/{sourceId}/{slug}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - 'Page IT'
      -
        - urlFormat
        - '{alias(''@livePreviewUrl'')}/it/techniques-d-animation/{sourceId}/{slug}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - 'Page DE'
      -
        - urlFormat
        - '{alias(''@livePreviewUrl'')}/de/techniques-d-animation/{sourceId}/{slug}'
      -
        - refresh
        - '1'
propagationMethod: custom
siteSettings:
  4cda444a-a132-4409-8e1e-5205e6a53896: # Puppetplays IT
    enabledByDefault: false
    hasUrls: true
    template: null
    uriFormat: 'techniques-d-animation/{sourceId}/{slug}'
  397a9f9f-ff18-42c4-98ff-dbb87c17b754: # Puppetplays FR
    enabledByDefault: false
    hasUrls: true
    template: null
    uriFormat: 'techniques-d-animation/{sourceId}/{slug}'
  59986aab-e6c1-4cdf-a062-8db833d2b327: # Puppetplays EN
    enabledByDefault: false
    hasUrls: true
    template: null
    uriFormat: 'techniques-d-animation/{sourceId}/{slug}'
  bf194204-844c-4373-ad71-db3f6243b824: # Puppetplays DE
    enabledByDefault: false
    hasUrls: true
    template: null
    uriFormat: 'techniques-d-animation/{sourceId}/{slug}'
type: channel
